apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    app: my-nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /usr/share/nginx/html
  - name: prometheus-exporter
    image: nginx/nginx-prometheus-exporter:1.1.0
    ports:
    - containerPort: 9113
  volumes:
  - name: config-volume
    configMap:
      name: nginx-config 
